version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "file": "%(filename)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  
  file_detailed:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/streamlit_demo_detailed.log
    mode: a
  
  file_user_interactions:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: logs/user_interactions.log
    mode: a
  
  file_errors:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    mode: a

loggers:
  streamlit_demo:
    level: DEBUG
    handlers: [console, file_detailed, file_errors]
    propagate: false
  
  user_interactions:
    level: INFO
    handlers: [file_user_interactions]
    propagate: false
  
  performance:
    level: INFO
    handlers: [file_detailed]
    propagate: false

root:
  level: INFO
  handlers: [console, file_detailed] 